In [5]:
%cd "/content/drive/My Drive/DL"
!ls


/content/drive/My Drive/DL
'40436_STMICROELECTRONICS_Eval Stagiaire.pdf'
 data
 DL07-01-sanity-check.py
 DL07-02-validate.py
 DL08-01-perceptron-without-activation.py
 DL08-02-activations.py
 DL08-03-perceptron.py
 DL08-06-mlp.py
 DL09-00-first-keras.py
 DL09-01-keras-and.py
 DL09-02-keras-add.py
 DL09-03-sequential.py
 DL09-04-functional.py
 DL09-05-compile-rms.py
 DL09-07-cancer-validation-keras.py
 DL09-07-cancer-validation-sklearn.py
 DL09-08-tp-mnist-badconverge-correction.py
 DL09-12-cancer-binary-crossentropy.py
 DL09-12-tp-mnist-crossentropy-correction.py
 DL09-13-repartition-proba.py
 DL09-14-cancer-softmax.py
 DL09-14-tp-mnist-softmax.py
 DL09-15-cancer-sgd.py
 DL09-17-cancer-customloss.py
 DL09-21-tp-mnist-dropout-correction.py
 DL09-22-validate-gpu.py
 DL09-23-dogsvscats.py
 DL09-24-tp-drivers-correction.py
 DL10-02-chollet-cnndemo.py
 DL10-03-chollet-summary.py
 DL10-05-lecun-sequential.py
 DL10-06-chollet-sequential.py
 DL10-08-MNIST-CNN.py
 DL10-09-tp-drivers-CNN-correct

In [24]:
from sklearn.datasets import load_breast_cancer
import tensorflow.keras as keras
import numpy as np
import tensorflow as tf
import sklearn.preprocessing

In [8]:
cancer = load_breast_cancer() # more info : https://goo.gl/U2Uwz2
X=cancer['data']
y=cancer['target']

print(X)
print(y)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 

In [29]:
scaler = sklearn.preprocessing.RobustScaler()
scaler.fit(X)
X = scaler.transform(X)

In [31]:
model = keras.Sequential([
    keras.layers.Dense(30, input_shape=(X.shape[1],), activation=tf.nn.relu),
    keras.layers.Dense(30, activation=tf.nn.relu),
    keras.layers.Dense(30, activation=tf.nn.relu),
    keras.layers.Dense(1, activation=tf.nn.sigmoid)
  ])

model.compile(loss="mse", metrics="accuracy" )
model.summary()

Model: "sequential_8"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_32 (Dense)             (None, 30)                930       
_________________________________________________________________
dense_33 (Dense)             (None, 30)                930       
_________________________________________________________________
dense_34 (Dense)             (None, 30)                930       
_________________________________________________________________
dense_35 (Dense)             (None, 1)                 31        
Total params: 2,821
Trainable params: 2,821
Non-trainable params: 0
_________________________________________________________________


In [33]:
history = model.fit(X, y, epochs=200, batch_size=10,  validation_split=0.2)


Epoch 1/200
46/46 [==============================] - 0s 7ms/step - loss: 0.1400 - accuracy: 0.8527 - val_loss: 0.0751 - val_accuracy: 0.9474
Epoch 2/200
46/46 [==============================] - 0s 5ms/step - loss: 0.0508 - accuracy: 0.9538 - val_loss: 0.0410 - val_accuracy: 0.9737
Epoch 3/200
46/46 [==============================] - 0s 5ms/step - loss: 0.0332 - accuracy: 0.9648 - val_loss: 0.0323 - val_accuracy: 0.9825
Epoch 4/200
46/46 [==============================] - 0s 5ms/step - loss: 0.0278 - accuracy: 0.9626 - val_loss: 0.0280 - val_accuracy: 0.9825
Epoch 5/200
46/46 [==============================] - 0s 5ms/step - loss: 0.0230 - accuracy: 0.9714 - val_loss: 0.0272 - val_accuracy: 0.9825
Epoch 6/200
46/46 [==============================] - 0s 5ms/step - loss: 0.0189 - accuracy: 0.9758 - val_loss: 0.0237 - val_accuracy: 0.9825
Epoch 7/200
46/46 [==============================] - 0s 5ms/step - loss: 0.0172 - accuracy: 0.9780 - val_loss: 0.0264 - val_accuracy: 0.9825
Epoch 8/200
4

In [11]:
predicted = model.predict(X)
print(model.evaluate(X,y))

18/18 [==============================] - 0s 2ms/step - loss: 1.0856 - accuracy: 0.3216
[1.0855610370635986, 0.32161685824394226]


In [12]:
predicted = np.where(predicted > 0.5,1,0)
predicted = predicted.reshape(-1)

print(predicted)
errors = predicted - y
print(errors)
print(len(errors[errors == 0]) / len(y))


[1 0 0 1 0 1 0 0 0 0 0 1 0 0 0 0 1 1 1 0 0 0 0 1 1 0 0 0 1 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 0 1 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0
 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 